# Generated by Django 5.1.2 on 2024-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0002_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default='perfil-null.png', upload_to='imagens'),
        ),
    ]
