# Generated by Django 5.1.2 on 2024-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0003_alter_usuario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(default='imagens/perfil-null.png', upload_to='imagens'),
        ),
    ]
