# Generated by Django 5.1.2 on 2024-10-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_alter_usuario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('time_casa', models.CharField(max_length=50)),
                ('placar_casa', models.IntegerField(max_length=50)),
                ('time_visitante', models.CharField(max_length=50)),
                ('placar_visitante', models.IntegerField(max_length=50)),
                ('vencedor', models.CharField(max_length=50)),
                ('finalizado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bolao.usuario')),
            ],
        ),
    ]
