# Generated by Django 5.1.2 on 2024-10-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0005_palpite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palpite',
            name='placar_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='placar_visitante',
            field=models.IntegerField(default=0),
        ),
    ]
