# Generated by Django 5.1.2 on 2024-10-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0006_alter_palpite_placar_casa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('time_casa', models.CharField(max_length=50)),
                ('placar_casa', models.CharField(max_length=50)),
                ('time_visitante', models.CharField(max_length=50)),
                ('placar_visitante', models.CharField(max_length=50)),
                ('imagem_casa', models.ImageField(upload_to='emblemas_times')),
                ('imagem_fora', models.ImageField(upload_to='emblemas_times')),
                ('vencedor', models.CharField(max_length=50)),
            ],
        ),
    ]
