# Generated by Django 5.1.2 on 2024-10-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0008_alter_palpite_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodadaOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('time_casa', models.CharField(max_length=50)),
                ('placar_casa', models.IntegerField(default=0)),
                ('time_visitante', models.CharField(max_length=50)),
                ('placar_visitante', models.IntegerField(default=0)),
                ('vencedor', models.CharField(max_length=50)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
    ]
