# Generated by Django 5.1.2 on 2024-10-19 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0009_rodadaoriginal'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodada',
            name='palpite_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bolao.palpite'),
        ),
    ]
