# Generated by Django 5.1.2 on 2024-10-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0010_rodada_palpite_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='palpite_usuario',
        ),
        migrations.AddField(
            model_name='palpite',
            name='imagem_casa',
            field=models.ImageField(default=1, upload_to='emblemas_times'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palpite',
            name='imagem_fora',
            field=models.ImageField(default=True, upload_to='emblemas_times'),
            preserve_default=False,
        ),
    ]
