# Generated by Django 5.1.2 on 2024-10-20 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0011_remove_rodada_palpite_usuario_palpite_imagem_casa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalvarRodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='vencedor',
        ),
        migrations.AddField(
            model_name='rodada',
            name='preenchido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rodada',
            name='usuario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodada',
            name='rodada',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='bolao.salvarrodada'),
            preserve_default=False,
        ),
    ]
