# Generated by Django 5.1.2 on 2024-10-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0012_salvarrodada_remove_rodada_vencedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='rodada',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='usuario',
        ),
    ]
