# Generated by Django 5.1.2 on 2024-10-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0013_remove_rodada_rodada_remove_rodada_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalvarRodada',
        ),
    ]
