# Generated by Django 5.1.2 on 2024-10-20 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0014_delete_salvarrodada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalvarRodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='rodada',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodada',
            name='rodada',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bolao.salvarrodada'),
            preserve_default=False,
        ),
    ]
