# Generated by Django 5.1.2 on 2024-10-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0015_salvarrodada_rodada_usuario_rodada_rodada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodada',
            name='rodada',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='SalvarRodada',
        ),
    ]
