# Generated by Django 5.1.2 on 2024-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0017_verificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='verificado',
            field=models.BooleanField(default=True),
        ),
    ]
