# Generated by Django 5.1.2 on 2024-10-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0018_alter_verificacao_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
