# Generated by Django 5.1.2 on 2024-10-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0020_bloquearpartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='partida_atual',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='verificacao',
            name='partida_final',
            field=models.IntegerField(default=39),
        ),
    ]
