# Generated by Django 5.1.2 on 2024-10-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0021_alter_verificacao_partida_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpite',
            name='tipo_class',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
