# Generated by Django 5.1.2 on 2024-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0023_alter_palpite_tipo_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='partida_atual',
            field=models.IntegerField(default=32),
        ),
    ]
