# Generated by Django 5.1.2 on 2024-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0024_alter_verificacao_partida_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(default='imagens/perfil-null.png', upload_to='thumb_img'),
        ),
    ]
